---
language: python
python:
- '2.7'
install:
- 'pip install yamllint==1.23.0'
- 'pip install cfn-lint==0.33.1'
script:
- 'yamllint .'
- 'cfn-lint -i W2001 W6001 -t ''**/*.yaml''' # TODO get rid of check ignores
- 'find . -type f -name ''*.yaml'' | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;'
